"""update users table

Revision ID: 4ee4e4066bc4
Revises: b07aa4613fc7
Create Date: 2025-10-13 16:22:19.587400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee4e4066bc4'
down_revision: Union[str, Sequence[str], None] = 'b07aa4613fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.drop_column('token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column('users', sa.Column('token', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('email',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
    # ### end Alembic commands ###
