"""update users table

Revision ID: b07aa4613fc7
Revises: 207d7a68774c
Create Date: 2025-10-11 13:03:57.175625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07aa4613fc7'
down_revision: Union[str, Sequence[str], None] = '207d7a68774c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 's3_prefix')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('s3_prefix', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
